
mpaginate: 3
year: 2019
author: 's2426'
url: http://s2426.github.io/harfistka.eu.org
exclude: ['.gitignore',
          'CNAME',
          'Gemfile',
          'Gemfile.lock',
          'Gruntfile.js',
          'LICENSE.md',
          'README.md',
          'package.json',
          'css/src/',
          'css/min/',
          'node_modules/',
          'python/',
          'vendor',
          'tests.html'
          ]
  -
    scope:
      path: ''
    values:
      author: 's2426'
  -
    scope:
      path: 'pl-pl'
    values:
      language: pl-PL
  -
    scope:
      path: 'en'
    values:
      language: en