year: 2019
author: 's2426'
url: http://www.harfistka.eu.org
exclude: ['.gitignore',
          'CNAME',
          'Gemfile',
          'Gemfile.lock',
          'Gruntfile.js',
          'LICENSE.md',
          'README.md',
          'package.json',
          'css/src/',
          'css/min/',
          'node_modules/',
          'python/',
          'vendor',
          'tests.html'
          ]
defaults:
  -
    scope:
      path: ""
    values:
      author: 's2426'