year: 2019
author: 's2426'
url: http://www.rafael.picanco.nom.br
exclude: ['.gitignore',
          'CNAME',
          'cpicanco.github.io.sublime-project',
          'cpicanco.github.io.sublime-workspace',
          'Gemfile',
          'Gemfile.lock',
          'Gruntfile.js',
          'LICENSE.md',
          'README.md',
          'package.json',
          'css/src/',
          'css/min/',
          'node_modules/',
          'python/',
          'vendor',
          'tests.html'
          ]
defaults:
  -
    scope:
      path: ""
    values:
      author: 's2426'