en:
  title: Want music at your wedding?
  credential: Harpist
  content: >
    Can play at your wedding today!
pl-PL:
  title: Szukasz oprawy muzycznej na ślub?
  credential: Harfistka
  content: >
    Może zagrać na Twoim ślubie jeszcze dziś!