en:
  title: Want music at wedding?
  credential: Harpist
  content: >
    Can play at your wedding today!
pl-PL:
  title: Szukasz muzyki na ślub?
  credential: Harfistka
  content: >
    Może zagrać na Twoim ślubie jeszcze dziś!